package dbconverter.view.ui;

import dbconverter.common.constant.DBTypes;
import dbconverter.model.util.DBConvert;
import dbconverter.model.vo.DBParamsVO;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JTextField;
import javax.swing.filechooser.*;
/**
 *
 * @author daneelolivaw
 */
public class MainWindow extends javax.swing.JFrame {

    private DBParamsVO dbSourceParams;
    private DBParamsVO dbTargetParams;

    private JFileChooser fc;


    public MainWindow() {
        initComponents();

        // comboBox
        DefaultComboBoxModel dbTypes_source = new DefaultComboBoxModel(DBTypes.supportedSGBDR);
        DefaultComboBoxModel dbTypes_target = new DefaultComboBoxModel(DBTypes.supportedSGBDR);
        this.cbo_db_source_sgbdr.setModel(dbTypes_source);
        this.cbo_db_target_sgbdr.setModel(dbTypes_target);

        // création des value objects des paramètres propres à chaque DB
        // (server - port - dbType - dbName - user - password)
        // à partir des valeurs par défaut des champs de la view

        dbSourceParams = new DBParamsVO(this.tfd_db_source_server.getText(),
                                      getDBPortFromTextField(this.tfd_db_target_port),
                                      this.cbo_db_source_sgbdr.getSelectedItem().toString(),
                                      this.tfd_db_source_name.getText(),
                                      this.tfd_db_source_user.getText(),
                                      this.tfd_db_source_passwd.getText());
        
        dbTargetParams = new DBParamsVO(this.tfd_db_target_server.getText(),
                                      getDBPortFromTextField(this.tfd_db_target_port),
                                      this.cbo_db_source_sgbdr.getSelectedItem().toString(),
                                      this.tfd_db_target_name.getText(),
                                      this.tfd_db_target_user.getText(),
                                      this.tfd_db_target_passwd.getText());

        
        // affichage des connectionStrings correspondantes
        this.lbl_db_source_connectionString.setText(dbSourceParams.toString());
        this.lbl_db_target_connectionString.setText(dbTargetParams.toString());

    }


    /**
     * Valide un numéro de port en fonction de la valeur du texte
     * @param tf
     * @return
     */
    private int getDBPortFromTextField(JTextField tf){
        // TODO : valider => int, range, ...
        int result = 0;
        result = Integer.parseInt(tf.getText());
        return result;
    }


    /**
     * Met à jour l'affichage de la connectionString
     */
    private void updateSourceLabel(){
        this.lbl_db_source_connectionString.setText(dbSourceParams.toString());
    }

    private void updateTargetLabel(){
        this.lbl_db_target_connectionString.setText(dbTargetParams.toString());
    }

    /**
     * Sélection d'un fichier DB (Firebird, Access, ...)
     * @param src
     */
    private void selectFile(String src){

        fc = new JFileChooser();

        int returnVal = fc.showOpenDialog(MainWindow.this);


        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            // valable pour Firebird, Access, ...
            
            if(src.equals("SOURCE")){
                dbSourceParams.setDb_localFile(file.getAbsolutePath());
                this.tfd_db_source_name.setText(dbSourceParams.getDb_localFile());
                updateSourceLabel();
            }else if(src.equals("TARGET")){
                dbTargetParams.setDb_localFile(file.getAbsolutePath());
                this.tfd_db_target_name.setText(dbSourceParams.getDb_localFile());
                updateTargetLabel();
            }
        }

        
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_convert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnl_source = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbo_db_source_sgbdr = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfd_db_source_port = new javax.swing.JTextField();
        tfd_db_source_name = new javax.swing.JTextField();
        lbl_source_servFile = new javax.swing.JLabel();
        tfd_db_source_server = new javax.swing.JTextField();
        tfd_db_source_user = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfd_db_source_passwd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lbl_db_source_connectionString = new javax.swing.JLabel();
        pnl_target = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbo_db_target_sgbdr = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        lbl_db_target_connectionString = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfd_db_target_passwd = new javax.swing.JTextField();
        tfd_db_target_user = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfd_db_target_name = new javax.swing.JTextField();
        tfd_db_target_port = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lbl_target_srvFile = new javax.swing.JLabel();
        tfd_db_target_server = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_convert.setText("Convertir");
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24));
        jLabel1.setText("Conversion de base de données");

        pnl_source.setBackground(new java.awt.Color(204, 204, 204));
        pnl_source.setMaximumSize(new java.awt.Dimension(500, 500));
        pnl_source.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel2.setText("Source");

        cbo_db_source_sgbdr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_db_source_sgbdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_db_source_sgbdrActionPerformed(evt);
            }
        });

        jLabel3.setText("SGBDR");

        jLabel4.setText("Port");

        jLabel5.setText("Database");

        tfd_db_source_port.setText("8889");
        tfd_db_source_port.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_source_portFocusLost(evt);
            }
        });

        tfd_db_source_name.setText("dbconvert01");
        tfd_db_source_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_source_nameFocusLost(evt);
            }
        });

        lbl_source_servFile.setText("Serveur");

        tfd_db_source_server.setText("localhost");
        tfd_db_source_server.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_source_serverFocusLost(evt);
            }
        });

        tfd_db_source_user.setText("root");
        tfd_db_source_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_source_userFocusLost(evt);
            }
        });

        jLabel11.setText("Utilisateur");

        tfd_db_source_passwd.setText("root");
        tfd_db_source_passwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_source_passwdFocusLost(evt);
            }
        });

        jLabel12.setText("Mot de passe");

        lbl_db_source_connectionString.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        lbl_db_source_connectionString.setForeground(new java.awt.Color(153, 153, 153));
        lbl_db_source_connectionString.setText("<ConnectionString>");
        lbl_db_source_connectionString.setAutoscrolls(true);

        org.jdesktop.layout.GroupLayout pnl_sourceLayout = new org.jdesktop.layout.GroupLayout(pnl_source);
        pnl_source.setLayout(pnl_sourceLayout);
        pnl_sourceLayout.setHorizontalGroup(
            pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnl_sourceLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lbl_db_source_connectionString, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .add(jLabel12)
                    .add(jLabel11)
                    .add(lbl_source_servFile)
                    .add(jLabel2)
                    .add(pnl_sourceLayout.createSequentialGroup()
                        .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel3))
                        .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(pnl_sourceLayout.createSequentialGroup()
                                .add(73, 73, 73)
                                .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(tfd_db_source_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(tfd_db_source_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(tfd_db_source_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(tfd_db_source_server, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(24, 24, 24))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnl_sourceLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(cbo_db_source_sgbdr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(8, 8, 8))))
                    .add(pnl_sourceLayout.createSequentialGroup()
                        .add(132, 132, 132)
                        .add(tfd_db_source_passwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnl_sourceLayout.setVerticalGroup(
            pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnl_sourceLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pnl_sourceLayout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel3)
                        .add(4, 4, 4))
                    .add(cbo_db_source_sgbdr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbl_source_servFile)
                    .add(tfd_db_source_server, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(tfd_db_source_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(tfd_db_source_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(tfd_db_source_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_sourceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(tfd_db_source_passwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 42, Short.MAX_VALUE)
                .add(lbl_db_source_connectionString)
                .addContainerGap())
        );

        pnl_target.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel6.setText("Cible");

        cbo_db_target_sgbdr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_db_target_sgbdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_db_target_sgbdrActionPerformed(evt);
            }
        });

        jLabel7.setText("SGBDR");

        lbl_db_target_connectionString.setFont(new java.awt.Font("Lucida Grande", 2, 13));
        lbl_db_target_connectionString.setForeground(new java.awt.Color(153, 153, 153));
        lbl_db_target_connectionString.setText("<ConnectionString>");

        jLabel13.setText("Mot de passe");

        tfd_db_target_passwd.setText("root");
        tfd_db_target_passwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_target_passwdFocusLost(evt);
            }
        });

        tfd_db_target_user.setText("root");
        tfd_db_target_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_target_userFocusLost(evt);
            }
        });

        jLabel14.setText("Utilisateur");

        jLabel8.setText("Database");

        tfd_db_target_name.setText("dbconvert02");
        tfd_db_target_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_target_nameFocusLost(evt);
            }
        });

        tfd_db_target_port.setText("8889");
        tfd_db_target_port.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_target_portFocusLost(evt);
            }
        });

        jLabel9.setText("Port");

        lbl_target_srvFile.setText("Serveur");

        tfd_db_target_server.setText("localhost");
        tfd_db_target_server.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfd_db_target_serverFocusLost(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnl_targetLayout = new org.jdesktop.layout.GroupLayout(pnl_target);
        pnl_target.setLayout(pnl_targetLayout);
        pnl_targetLayout.setHorizontalGroup(
            pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnl_targetLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(lbl_target_srvFile)
                    .add(pnl_targetLayout.createSequentialGroup()
                        .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel9)
                            .add(jLabel8)
                            .add(jLabel13))
                        .add(48, 48, 48)
                        .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(tfd_db_target_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tfd_db_target_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tfd_db_target_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tfd_db_target_server, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tfd_db_target_passwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 213, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(pnl_targetLayout.createSequentialGroup()
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 81, Short.MAX_VALUE)
                        .add(cbo_db_target_sgbdr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 237, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(lbl_db_target_connectionString, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .add(jLabel6))
                .addContainerGap())
        );
        pnl_targetLayout.setVerticalGroup(
            pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnl_targetLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(cbo_db_target_sgbdr, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lbl_target_srvFile)
                    .add(tfd_db_target_server, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(tfd_db_target_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(tfd_db_target_name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(tfd_db_target_user, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnl_targetLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tfd_db_target_passwd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                .add(lbl_db_target_connectionString)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(layout.createSequentialGroup()
                        .add(pnl_source, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(pnl_target, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(746, Short.MAX_VALUE)
                .add(btn_convert)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnl_source, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnl_target, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(btn_convert)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed
        // lance le convertisseur
        DBConvert converter = new DBConvert(dbSourceParams,dbTargetParams);
    }//GEN-LAST:event_btn_convertActionPerformed

    private void cbo_db_source_sgbdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_db_source_sgbdrActionPerformed
        String dbTypeName = this.cbo_db_source_sgbdr.getSelectedItem().toString();
        dbSourceParams.setDb_typeName(dbTypeName);

        // Tentative de définition automatique du port en fonction du type de DB.
        // Peut varier d'un système d'exploitation à l'autre :
        // ex. MySQL Mac MAMP = 8889 / Linux LAMP = 3306, ...
        int dbPort = DBTypes.getDBDefaultPort(DBTypes.getDBTypeID(dbTypeName));
        this.tfd_db_source_port.setText(""+dbPort);
        dbSourceParams.setPort(dbPort);

        // Doit-on référencer un fichier pour la DB (Access, Firebird, ...) ?
        if(DBTypes.isFile(DBTypes.getDBTypeID(dbTypeName))){
            //this.lbl_source_servFile.setText("Fichier");
            selectFile("SOURCE");
        }else{
            //this.lbl_source_servFile.setText("Serveur");
        }

        updateSourceLabel();
    }//GEN-LAST:event_cbo_db_source_sgbdrActionPerformed

    private void cbo_db_target_sgbdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_db_target_sgbdrActionPerformed
        String dbTypeName = this.cbo_db_target_sgbdr.getSelectedItem().toString();
        dbTargetParams.setDb_typeName(dbTypeName);

        // Tentative de définition automatique du port en fonction du type de DB.
        // Peut varier d'un système d'exploitation à l'autre :
        // ex. MySQL Mac MAMP = 8889 / Linux LAMP = 3306, ...
        int dbPort = DBTypes.getDBDefaultPort(DBTypes.getDBTypeID(dbTypeName));
        
        // Doit-on référencer un fichier pour la DB (Access, Firebird, ...)
        if(DBTypes.isFile(DBTypes.getDBTypeID(dbTypeName))){
            this.lbl_target_srvFile.setText("Fichier");
            selectFile("TARGET");
        }else{
            this.lbl_target_srvFile.setText("Serveur");
        }

        this.tfd_db_target_port.setText(""+dbPort);
        dbTargetParams.setPort(dbPort);

        updateTargetLabel();
    }//GEN-LAST:event_cbo_db_target_sgbdrActionPerformed


    private void tfd_db_source_portFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_source_portFocusLost
        dbSourceParams.setPort(getDBPortFromTextField(this.tfd_db_source_port));
        // System.out.println("PORT : " + getDBPortFromTextField(this.tfd_db_source_port));
        updateSourceLabel();
    }//GEN-LAST:event_tfd_db_source_portFocusLost

    private void tfd_db_source_serverFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_source_serverFocusLost
        dbSourceParams.setServer(this.tfd_db_source_server.getText());
        updateSourceLabel();
    }//GEN-LAST:event_tfd_db_source_serverFocusLost

    private void tfd_db_source_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_source_nameFocusLost
        dbSourceParams.setDb_name(this.tfd_db_source_name.getText());
        updateSourceLabel();
    }//GEN-LAST:event_tfd_db_source_nameFocusLost

    private void tfd_db_source_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_source_userFocusLost
        dbSourceParams.setUser(this.tfd_db_source_user.getText());
    }//GEN-LAST:event_tfd_db_source_userFocusLost

    private void tfd_db_source_passwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_source_passwdFocusLost
        dbSourceParams.setPassword(this.tfd_db_source_passwd.getText());
    }//GEN-LAST:event_tfd_db_source_passwdFocusLost

    private void tfd_db_target_serverFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_target_serverFocusLost
        dbTargetParams.setServer(this.tfd_db_target_server.getText());
        updateTargetLabel();
    }//GEN-LAST:event_tfd_db_target_serverFocusLost

    private void tfd_db_target_portFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_target_portFocusLost
        dbTargetParams.setPort(getDBPortFromTextField(this.tfd_db_target_port));
        updateTargetLabel();
    }//GEN-LAST:event_tfd_db_target_portFocusLost

    private void tfd_db_target_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_target_nameFocusLost
        dbTargetParams.setDb_name(this.tfd_db_target_name.getText());
        updateTargetLabel();
    }//GEN-LAST:event_tfd_db_target_nameFocusLost

    private void tfd_db_target_userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_target_userFocusLost
        dbTargetParams.setUser(this.tfd_db_target_user.getText());
    }//GEN-LAST:event_tfd_db_target_userFocusLost

    private void tfd_db_target_passwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfd_db_target_passwdFocusLost
        dbTargetParams.setPassword(this.tfd_db_target_passwd.getText());
    }//GEN-LAST:event_tfd_db_target_passwdFocusLost




    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_convert;
    private javax.swing.JComboBox cbo_db_source_sgbdr;
    private javax.swing.JComboBox cbo_db_target_sgbdr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_db_source_connectionString;
    private javax.swing.JLabel lbl_db_target_connectionString;
    private javax.swing.JLabel lbl_source_servFile;
    private javax.swing.JLabel lbl_target_srvFile;
    private javax.swing.JPanel pnl_source;
    private javax.swing.JPanel pnl_target;
    private javax.swing.JTextField tfd_db_source_name;
    private javax.swing.JTextField tfd_db_source_passwd;
    private javax.swing.JTextField tfd_db_source_port;
    private javax.swing.JTextField tfd_db_source_server;
    private javax.swing.JTextField tfd_db_source_user;
    private javax.swing.JTextField tfd_db_target_name;
    private javax.swing.JTextField tfd_db_target_passwd;
    private javax.swing.JTextField tfd_db_target_port;
    private javax.swing.JTextField tfd_db_target_server;
    private javax.swing.JTextField tfd_db_target_user;
    // End of variables declaration//GEN-END:variables

}
